const allConfig = {
    lengendList:[
        {
           name:'mode',
           title:'模块',
           svgName:'范围'
        },
        {
            name:'entity',
            title:'实物',
            svgName:'矩形'
         },
         {
            name:'ellipse',
            title:'供应商',
            svgName:'椭圆'
         },
         {
            name:'triangle',
            title:'业务线',
            svgName:'三角形'
         },
         {
            name:'label',
            title:'标注',
            svgName:'标注'
         },
         {
            name:'flag',
            title:'关键点',
            svgName:'旗帜'
         },
         {
            name:'danger',
            title:'风险点',
            svgName:'注意'
         },
    ]
}
export default allConfig